# Generated by Django 5.0.1 on 2024-01-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.car', verbose_name='машина'),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.moto', verbose_name='мотоцикл'),
        ),
    ]
